filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /*.log
    multiline.pattern: ^\[
    multiline.match: after
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
setup.kibana:
output.logstash:
  hosts: [ "logstash:5044" ]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~