version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos-standalone-mysql
    env_file:
      - /www/server/docker-srv/nacos/nacos-docker/env/nacos-standlone-mysql.env
    volumes:
      - /www/server/docker-srv/nacos/standalone-logs/:/home/nacos/logs
      - /www/server/docker-srv/nacos/nacos-docker/build/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    # depends_on:
    #   - mysql
    restart: always
  # mysql:
  #   container_name: mysql
  #   image: nacos/nacos-mysql:8.0.16
  #   env_file:
  #     - ../env/mysql.env
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"


