# yaml 配
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.60:9092
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  kafka-manager:
#    container_name: sheepkiller/kafka-manager
#    image: docker.io/sheepkiller/kafka-manager
#    network_mode: host
#    restart: on-failure
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - 9000:9000